name: 热点推送机器人

on:
  schedule:
    - cron: '30 2 * * *'
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  push-hot-topics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 运行脚本
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        run: python hot_push_v3.py
